// <auto-generated />
using System;
using AquaDefender_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AquaDefender_Backend.Data.Migrations
{
    [DbContext(typeof(AquaDefenderDataContext))]
    [Migration("20240325085735_ChangedFloatToStringWaterValues")]
    partial class ChangedFloatToStringWaterValues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AquaDefender_Backend.Domain.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("CountyId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CountyId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AquaDefender_Backend.Domain.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityHallEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountyId");

                    b.ToTable("City");
                });

            modelBuilder.Entity("AquaDefender_Backend.Domain.County", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WaterDeptEmail")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("County");
                });

            modelBuilder.Entity("AquaDefender_Backend.Domain.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("CountyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("LocationDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CountyId");

                    b.HasIndex("UserId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("AquaDefender_Backend.Domain.ReportImage", b =>
                {
                    b.Property<int>("IdImage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdImage"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.HasKey("IdImage");

                    b.HasIndex("ReportId");

                    b.ToTable("ReportImage");
                });

            modelBuilder.Entity("AquaDefender_Backend.Domain.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("AquaDefender_Backend.Domain.WaterInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acrilamida")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActivitateaAlfaGlobala")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActivitateaBetaGlobala")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdditionalNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aluminiu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Amoniu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Arsen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BacteriiColiforme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BenzAPiren")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Benzen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bromati")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cadmiu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarbonOrganicTotal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CianuriLibere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CianuriTotale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("ClorRezidualLiber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CloruraDeVinil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cloruri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClostridiumPerfringens")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Conductivitate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountyId")
                        .HasColumnType("int");

                    b.Property<string>("CromTotal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Culoare")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cupru")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateReported")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dicloretan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DozaEfectivaTotalaDeReferinta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DuritateTotala")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Enterococi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Epiclorhidrina")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EscherichiaColi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fluoruri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gust")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HidrocarburiPolicicliceAromatice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mangan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mercur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Miros")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nichel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nitrati")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nitriti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumarColonii22C")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumarColonii37C")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Oxidabilitate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pesticide")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PesticideTotal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plumb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PseudomonasAeruginosa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Seleniu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sodiu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stibiu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sulfat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SulfuriSiHidrogenSulfurat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TetracloretenaSiTricloretena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrihalometaniTotal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tritiu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Turbiditate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zinc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CountyId");

                    b.ToTable("WaterInfos");
                });

            modelBuilder.Entity("AquaDefender_Backend.Domain.AppUser", b =>
                {
                    b.HasOne("AquaDefender_Backend.Domain.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AquaDefender_Backend.Domain.County", "County")
                        .WithMany()
                        .HasForeignKey("CountyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AquaDefender_Backend.Domain.UserRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("County");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AquaDefender_Backend.Domain.City", b =>
                {
                    b.HasOne("AquaDefender_Backend.Domain.County", "County")
                        .WithMany("Cities")
                        .HasForeignKey("CountyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("County");
                });

            modelBuilder.Entity("AquaDefender_Backend.Domain.Report", b =>
                {
                    b.HasOne("AquaDefender_Backend.Domain.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AquaDefender_Backend.Domain.County", "County")
                        .WithMany()
                        .HasForeignKey("CountyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AquaDefender_Backend.Domain.AppUser", "User")
                        .WithMany("Reports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("County");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AquaDefender_Backend.Domain.ReportImage", b =>
                {
                    b.HasOne("AquaDefender_Backend.Domain.Report", "Report")
                        .WithMany("Images")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("AquaDefender_Backend.Domain.WaterInfo", b =>
                {
                    b.HasOne("AquaDefender_Backend.Domain.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AquaDefender_Backend.Domain.County", "County")
                        .WithMany()
                        .HasForeignKey("CountyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("County");
                });

            modelBuilder.Entity("AquaDefender_Backend.Domain.AppUser", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("AquaDefender_Backend.Domain.County", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("AquaDefender_Backend.Domain.Report", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
